### ISSUE TITLE
Videos of 2D skeletal poses

### ISSUE THREAD

**Issue by athena913** [how2sign/how2sign.github.io#13]
Hi, 

In the sentence_level/*/rgb_front/openpose_output/video/  folders, there are videos of the skeletal poses (from the rgb_front_2D_keypoints data). Is it possible to provide the code that was used to create these skeletal videos? I would like to know how to identify the joints and connect them, so I can try it on a different dataset. Thanks.

**Comment by athena913** [comment]
This is perhaps done using the OpenPose API. So will close this issue.

**Comment by mandacduarte** [comment]
Hi @athena913 
as stated in the paper, the skeletons were extracted using OpenPose library. 
You can go directly to their github repo and you will find how to identify and connect them.
Hope that helps.
Thanks,
