### ISSUE TITLE
English Translation links not working?

### ISSUE THREAD

**Issue by henrique** [how2sign/how2sign.github.io#4]
<div class="row">
                <div class="col-2 titlecol"> English Translation </div>
                <div class="col-10" style="padding:0">
                  <div class="col-4">
                    <a href="">
                      <button class="button" disabled="">Train</button>
                    </a>
                  </div>
                  <div class="col-4">
                    <a href="">
                      <button class="button" disabled="">Validation</button>
                    </a>
                  </div>
                  <div class="col-4">
                    <a href="">
                      <button class="button" disabled="">Test</button>
                    </a>
                  </div>
                </div>
              </div>
              
              
              
same for B-F-H 2D Keypoints  (side view)

thanks for the amazing work, though!

**Comment by how2sign** [comment]
Hi, 
sorry for the late reply. 
You can find the English translation now available on the [How2Sign website](https://how2sign.github.io/) for download as well as the start and end timestamps for each sentence in the same file. 

We are still working on having the B-F-H 2D Keypoints (side view) ready to make it available. 
It will hopefully be available soon!

Thank you,
