### ISSUE TITLE
I'm facing the forbidden problem while downloading the train (31 GB) of Green Screen RGB clips* (frontal view)? How can I sove this?

### ISSUE THREAD

**Issue by hlaingmyatnwe** [how2sign/how2sign.github.io#6]

**Comment by mandacduarte** [comment]
Hi, 
you can download the "Green Screen RGB clips* (frontal view)" training set in smaller zip files at this link:
https://drive.google.com/drive/folders/13ctlZTuZr6HU4N4a6NADb9ZoFRedP22w?usp=sharing

Please let me know if you have any problems with that.
Best,

**Comment by hlaingmyatnwe** [comment]
Thank you for your sharing. 
I downloaded **train_raw_videos.zip** files from your link and then I got only 158 videos.
In **how2sign_realigned_train.csv** file, there are 2,638 video file.
Do I need to download all files in smaller zip files?

**Comment by mandacduarte** [comment]
Yes, 
you should download and merge all of them before extracting the videos from the file.

**Comment by keniel123** [comment]
Hi @mandacduarte 

I tried accessing the folder to download the frontal clips however the folder is empty
