### ISSUE TITLE
Clips by English Translation

### ISSUE THREAD

**Issue by shngt** [how2sign/how2sign.github.io#9]
Hi, the website mentions that "The manual re-alignment of the English translation with the ASL videos will be released soon!". Is there any tentative timeline by which this will happen, and could you please clarify what exactly will be made available?

Thank you for the great dataset!

**Comment by how2sign** [comment]
Hi,
thank you for pointing that out, it is in fact old information that needs to be corrected. 

You can find the manually re-aligned English translation at the bottom of the download list in the "Download section" under the name (English Translation (manually re-aligned)).
You will find in those files, the English translation, and the start and end timestamp of each sentence with respect to the Green Screen RGB videos.
To obtain the clips with the re-aligned timestamps, please use the start and end timestamps to cut the RGB videos into clips.

Let me know if you have any problems regarding that.

Thank you,
